apiVersion: batch/v1
kind: Job
metadata:
  name: light-edit-mvhuman-job
spec:
  parallelism: 5
  completions: 5
  completionMode: Indexed
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-GeForce-RTX-4090
                - NVIDIA-A10
      restartPolicy: Never
      containers:
        - name: python-container
          image: python:3.10.16-bullseye
          command: 
          - "/bin/bash"
          - "-c"
          - |
            export start=$((100 * $JOB_COMPLETION_INDEX))
            export end=$((start + 100))
            echo $start
            echo $end
            export INPUT_DIR=/data/mvhuman_data/mv_captures
            export OUTPUT_DIR=/data/light-edit-mvhuman
            git clone https://github.com/ginlov/light-synthesis.git
            cd light-synthesis
            apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
            pip install -r requirements.txt
            echo "Processing folders from $start to $end"
            python ic_light.py --input_dir $INPUT_DIR --out_path $OUTPUT_DIR --start $start --end $end
          env:
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          resources:
            requests:
              cpu: "16"
              memory: "32Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "16"
              memory: "32Gi"
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /data
              name: data-volume
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: mvhumannet-dataset